spring:
  datasource:
    driver-class-name: org.sqlite.JDBC
    url: jdbc:sqlite:file:company.db
    dbcp:
      max-active: 1
      max-idle: 1
      pool-prepared-statements: true
      initial-size: 1
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLiteDialect

http:
  custom:
    timeout: 60000